package bleephub

import (
	"fmt"
	"net/http"
	"strings"
)

func (s *Server) registerGHTemplateRoutes() {
	s.route("GET /api/v3/gitignore/templates", s.handleListGitignoreTemplates)
	s.route("GET /api/v3/gitignore/templates/{name}", s.handleGetGitignoreTemplate)
	s.route("GET /api/v3/licenses", s.handleListLicenses)
	s.route("GET /api/v3/licenses/{license}", s.handleGetLicense)
}

func (s *Server) handleListGitignoreTemplates(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, listGitignoreNames())
}

func (s *Server) handleGetGitignoreTemplate(w http.ResponseWriter, r *http.Request) {
	name := r.PathValue("name")
	canonical, ok := normalizeGitignoreName(name)
	if !ok {
		writeGHError(w, http.StatusNotFound, "Not Found")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"name":   canonical,
		"source": gitignoreTemplates[canonical],
	})
}

func (s *Server) handleListLicenses(w http.ResponseWriter, r *http.Request) {
	keys := listLicenseKeys()
	out := make([]map[string]interface{}, 0, len(keys))
	for _, k := range keys {
		tmpl := licenseTemplates[k]
		out = append(out, map[string]interface{}{
			"key":     k,
			"name":    tmpl.name,
			"spdx_id": tmpl.spdxID,
			"url":     s.baseURL(r) + "/api/v3/licenses/" + k,
			"node_id": "MDc6TGljZW5zZ" + k,
		})
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) handleGetLicense(w http.ResponseWriter, r *http.Request) {
	key := strings.ToLower(r.PathValue("license"))
	tmpl, ok := licenseTemplates[key]
	if !ok {
		writeGHError(w, http.StatusNotFound, "Not Found")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"key":            key,
		"name":           tmpl.name,
		"spdx_id":        tmpl.spdxID,
		"body":           tmpl.body,
		"description":    tmpl.name,
		"implementation": "",
		"permissions":    []string{},
		"conditions":     []string{},
		"limitations":    []string{},
		"featured":       true,
		"html_url":       "https://choosealicense.com/licenses/" + key + "/",
		"node_id":        "MDc6TGljZW5zZTEz",
		"url":            s.baseURL(r) + "/api/v3/licenses/" + key,
	})
}

// gitignoreTemplates is a curated list of common .gitignore templates
// matching the names GitHub serves from https://github.com/github/gitignore.
// The content is real, recognizable template text.
var gitignoreTemplates = map[string]string{
	"Go": `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with go test -c
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
`,
	"Node": `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/

# Dependency directories
node_modules/

# TypeScript cache
*.tsbuildinfo
`,
	"Python": `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
`,
	"Java": `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*
`,
	"Ruby": `*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
.env

## Specific to RubyMotion:
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/
`,
	"Rust": `# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk
`,
	"VisualStudio": `## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/
`,
}

func listGitignoreNames() []string {
	names := make([]string, 0, len(gitignoreTemplates))
	for name := range gitignoreTemplates {
		names = append(names, name)
	}
	return names
}

// licenseTemplates is a curated list of common open-source license keys and
// full texts. Keys match the SPDX identifiers GitHub accepts in the
// license_template field of repo creation.
var licenseTemplates = map[string]struct {
	name   string
	spdxID string
	body   string
}{
	"mit": {
		name:   "MIT License",
		spdxID: "MIT",
		body: `MIT License

Copyright (c) [year] [fullname]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`,
	},
	"apache-2.0": {
		name:   "Apache License 2.0",
		spdxID: "Apache-2.0",
		body: `Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`,
	},
	"gpl-3.0": {
		name:   "GNU General Public License v3.0",
		spdxID: "GPL-3.0",
		body: `GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
`,
	},
	"bsd-2-clause": {
		name:   "BSD 2-Clause \"Simplified\" License",
		spdxID: "BSD-2-Clause",
		body: `BSD 2-Clause License

Copyright (c) [year], [fullname]
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
`,
	},
	"bsd-3-clause": {
		name:   "BSD 3-Clause \"New\" or \"Revised\" License",
		spdxID: "BSD-3-Clause",
		body: `BSD 3-Clause License

Copyright (c) [year], [fullname]
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
`,
	},
	"mpl-2.0": {
		name:   "Mozilla Public License 2.0",
		spdxID: "MPL-2.0",
		body: `Mozilla Public License Version 2.0
==================================

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
`,
	},
	"unlicense": {
		name:   "The Unlicense",
		spdxID: "Unlicense",
		body: `This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
`,
	},
}

func listLicenseKeys() []string {
	keys := make([]string, 0, len(licenseTemplates))
	for k := range licenseTemplates {
		keys = append(keys, k)
	}
	return keys
}

func normalizeLicenseKey(key string) (string, bool) {
	lower := strings.ToLower(key)
	if _, ok := licenseTemplates[lower]; ok {
		return lower, true
	}
	return "", false
}

func normalizeGitignoreName(name string) (string, bool) {
	for k := range gitignoreTemplates {
		if strings.EqualFold(k, name) {
			return k, true
		}
	}
	return "", false
}

func licenseBody(key, owner, repo string, year int) string {
	tmpl := licenseTemplates[key]
	body := strings.ReplaceAll(tmpl.body, "[year]", fmt.Sprintf("%d", year))
	body = strings.ReplaceAll(body, "[fullname]", owner)
	return body
}
