// Code generated by check-backend-coverage --generate; DO NOT EDIT.
// These delegate methods ensure every api.Backend method is explicitly
// declared on Server. Replace any delegate with a cloud-native
// implementation when ready.

package azf

import (
	"github.com/sockerless/api"
	"io"
)

func (s *Server) ContainerChanges(id string) ([]api.ContainerChangeItem, error) {
	return s.BaseServer.ContainerChanges(id)
}

func (s *Server) ContainerGetArchive(id string, path string) (*api.ContainerArchiveResponse, error) {
	return s.BaseServer.ContainerGetArchive(id, path)
}

func (s *Server) ContainerInspect(id string) (*api.Container, error) {
	return s.BaseServer.ContainerInspect(id)
}

func (s *Server) ContainerList(opts api.ContainerListOptions) ([]*api.ContainerSummary, error) {
	return s.BaseServer.ContainerList(opts)
}

func (s *Server) ContainerPutArchive(id string, path string, noOverwriteDirNonDir bool, body io.Reader) error {
	return s.BaseServer.ContainerPutArchive(id, path, noOverwriteDirNonDir, body)
}

func (s *Server) ContainerRename(id string, newName string) error {
	return s.BaseServer.ContainerRename(id, newName)
}

func (s *Server) ContainerResize(id string, h int, w int) error {
	return s.BaseServer.ContainerResize(id, h, w)
}

func (s *Server) ContainerStatPath(id string, path string) (*api.ContainerPathStat, error) {
	return s.BaseServer.ContainerStatPath(id, path)
}

func (s *Server) ContainerStats(id string, stream bool) (io.ReadCloser, error) {
	return s.BaseServer.ContainerStats(id, stream)
}

func (s *Server) ContainerTop(id string, psArgs string) (*api.ContainerTopResponse, error) {
	return s.BaseServer.ContainerTop(id, psArgs)
}

func (s *Server) ContainerUpdate(id string, req *api.ContainerUpdateRequest) (*api.ContainerUpdateResponse, error) {
	return s.BaseServer.ContainerUpdate(id, req)
}

func (s *Server) ContainerWait(id string, condition string) (*api.ContainerWaitResponse, error) {
	return s.BaseServer.ContainerWait(id, condition)
}

func (s *Server) ExecCreate(containerID string, req *api.ExecCreateRequest) (*api.ExecCreateResponse, error) {
	return s.BaseServer.ExecCreate(containerID, req)
}

func (s *Server) ExecInspect(id string) (*api.ExecInstance, error) {
	return s.BaseServer.ExecInspect(id)
}

func (s *Server) ExecResize(id string, h int, w int) error {
	return s.BaseServer.ExecResize(id, h, w)
}

func (s *Server) ExecStart(id string, opts api.ExecStartRequest) (io.ReadWriteCloser, error) {
	return s.BaseServer.ExecStart(id, opts)
}

func (s *Server) ImageHistory(name string) ([]*api.ImageHistoryEntry, error) {
	return s.BaseServer.ImageHistory(name)
}

func (s *Server) ImageInspect(name string) (*api.Image, error) {
	return s.BaseServer.ImageInspect(name)
}

func (s *Server) ImageList(opts api.ImageListOptions) ([]*api.ImageSummary, error) {
	return s.BaseServer.ImageList(opts)
}

func (s *Server) ImagePrune(filters map[string][]string) (*api.ImagePruneResponse, error) {
	return s.BaseServer.ImagePrune(filters)
}

func (s *Server) ImageSave(names []string) (io.ReadCloser, error) {
	return s.BaseServer.ImageSave(names)
}

func (s *Server) ImageSearch(term string, limit int, filters map[string][]string) ([]*api.ImageSearchResult, error) {
	return s.BaseServer.ImageSearch(term, limit, filters)
}

func (s *Server) NetworkConnect(id string, req *api.NetworkConnectRequest) error {
	return s.BaseServer.NetworkConnect(id, req)
}

func (s *Server) NetworkCreate(req *api.NetworkCreateRequest) (*api.NetworkCreateResponse, error) {
	return s.BaseServer.NetworkCreate(req)
}

func (s *Server) NetworkDisconnect(id string, req *api.NetworkDisconnectRequest) error {
	return s.BaseServer.NetworkDisconnect(id, req)
}

func (s *Server) NetworkInspect(id string) (*api.Network, error) {
	return s.BaseServer.NetworkInspect(id)
}

func (s *Server) NetworkList(filters map[string][]string) ([]*api.Network, error) {
	return s.BaseServer.NetworkList(filters)
}

func (s *Server) NetworkPrune(filters map[string][]string) (*api.NetworkPruneResponse, error) {
	return s.BaseServer.NetworkPrune(filters)
}

func (s *Server) NetworkRemove(id string) error {
	return s.BaseServer.NetworkRemove(id)
}

func (s *Server) PodCreate(req *api.PodCreateRequest) (*api.PodCreateResponse, error) {
	return s.BaseServer.PodCreate(req)
}

func (s *Server) PodExists(name string) (bool, error) {
	return s.BaseServer.PodExists(name)
}

func (s *Server) PodInspect(name string) (*api.PodInspectResponse, error) {
	return s.BaseServer.PodInspect(name)
}

func (s *Server) PodList(opts api.PodListOptions) ([]*api.PodListEntry, error) {
	return s.BaseServer.PodList(opts)
}

func (s *Server) SystemDf() (*api.DiskUsageResponse, error) {
	return s.BaseServer.SystemDf()
}

func (s *Server) SystemEvents(opts api.EventsOptions) (io.ReadCloser, error) {
	return s.BaseServer.SystemEvents(opts)
}

func (s *Server) VolumeCreate(req *api.VolumeCreateRequest) (*api.Volume, error) {
	return s.BaseServer.VolumeCreate(req)
}

func (s *Server) VolumeInspect(name string) (*api.Volume, error) {
	return s.BaseServer.VolumeInspect(name)
}

func (s *Server) VolumeList(filters map[string][]string) (*api.VolumeListResponse, error) {
	return s.BaseServer.VolumeList(filters)
}

func (s *Server) VolumePrune(filters map[string][]string) (*api.VolumePruneResponse, error) {
	return s.BaseServer.VolumePrune(filters)
}

func (s *Server) VolumeRemove(name string, force bool) error {
	return s.BaseServer.VolumeRemove(name, force)
}
