package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// InstanceLifecycle shells out to the per-component make targets (see
// make/components.mk) to start / stop / rebuild a single instance.
// Stays out of the in-process topology lock — callers grab the
// instance via TopologyManager first, then drive lifecycle here.
//
// repoRoot is the directory the make commands run in. Empty string
// uses the process's current working dir (the typical case when
// admin is launched from the repo root via `make stack-up`).
type InstanceLifecycle struct {
	repoRoot string
	timeout  time.Duration
}

// NewInstanceLifecycle constructs a lifecycle shell. timeout caps any
// single make invocation; 0 means no timeout.
func NewInstanceLifecycle(repoRoot string, timeout time.Duration) *InstanceLifecycle {
	if timeout == 0 {
		timeout = 5 * time.Minute
	}
	return &InstanceLifecycle{repoRoot: repoRoot, timeout: timeout}
}

// Start invokes `make start-component` with the per-instance
// arguments derived from inst + simPort (resolved by caller from the
// instance's Sim ref, when applicable).
func (l *InstanceLifecycle) Start(ctx context.Context, inst Instance, simPort int) error {
	args := []string{
		"start-component",
		"KIND=" + string(inst.Kind),
		"NAME=" + inst.Name,
		"PORT=" + strconv.Itoa(inst.Port),
	}
	if inst.Cloud != "" {
		args = append(args, "CLOUD="+string(inst.Cloud))
	}
	if inst.Backend != "" {
		args = append(args, "BACKEND="+string(inst.Backend))
	}
	if inst.Kind == InstanceKindBackend && simPort > 0 {
		args = append(args, "SIM_PORT="+strconv.Itoa(simPort))
	}
	if len(inst.Config) > 0 {
		envFile := envFilePath(l.repoRoot, inst.Name)
		if err := writeEnvFile(envFile, inst.Config); err != nil {
			return fmt.Errorf("write env file: %w", err)
		}
		args = append(args, "ENV_FILE="+envFile)
	}
	return l.runMake(ctx, args...)
}

// Stop invokes `make stop-component NAME=<inst.Name>`.
func (l *InstanceLifecycle) Stop(ctx context.Context, inst Instance) error {
	return l.runMake(ctx, "stop-component", "NAME="+inst.Name)
}

// Rebuild invokes `make rebuild-component KIND=… [CLOUD=…] [BACKEND=…]`.
func (l *InstanceLifecycle) Rebuild(ctx context.Context, inst Instance) error {
	args := []string{"rebuild-component", "KIND=" + string(inst.Kind)}
	if inst.Cloud != "" {
		args = append(args, "CLOUD="+string(inst.Cloud))
	}
	if inst.Backend != "" {
		args = append(args, "BACKEND="+string(inst.Backend))
	}
	return l.runMake(ctx, args...)
}

func (l *InstanceLifecycle) runMake(ctx context.Context, args ...string) error {
	if l.timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, l.timeout)
		defer cancel()
	}
	cmd := exec.CommandContext(ctx, "make", args...)
	if l.repoRoot != "" {
		cmd.Dir = l.repoRoot
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("make %s: %w (output: %s)",
			strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

func envFilePath(repoRoot, instanceName string) string {
	root := repoRoot
	if root == "" {
		if cwd, err := os.Getwd(); err == nil {
			root = cwd
		}
	}
	return filepath.Join(root, ".stack-pids", instanceName+".env")
}

// writeEnvFile renders cfg as a `KEY=VALUE` line per entry, sorted
// for deterministic output (admin Replace stays idempotent on the
// env-file write path).
func writeEnvFile(path string, cfg map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := sortedConfigKeys(cfg)
	var b strings.Builder
	b.WriteString("# generated by sockerless-admin; do not edit by hand\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(cfg[k])
		b.WriteByte('\n')
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func sortedConfigKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	// Avoid pulling sort into this file's deps unnecessarily; small N.
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j-1] > out[j]; j-- {
			out[j-1], out[j] = out[j], out[j-1]
		}
	}
	return out
}
