// Command check-backend-coverage verifies that every backend explicitly
// implements all methods from the api.Backend interface (not just inheriting
// them via embedding). This catches backends silently falling back to
// BaseServer's in-memory stubs instead of providing real cloud SDK
// implementations.
//
// Usage:
//
//	go run . [--enforce]   Report missing methods; exit 1 if any are missing
//	go run . --generate    Generate backend_delegates_gen.go for each backend
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// backendDef describes a backend to check.
type backendDef struct {
	name       string // display name
	dir        string // relative path from repo root
	receiver   string // receiver type name (e.g. "Server", "BaseServer")
	pkg        string // Go package name
	hasBasePtr bool   // embeds *core.BaseServer
}

var backends = []backendDef{
	{"core", "backends/core", "BaseServer", "core", false},
	{"docker", "backends/docker", "Server", "docker", false},
	{"ecs", "backends/ecs", "Server", "ecs", true},
	{"cloudrun", "backends/cloudrun", "Server", "cloudrun", true},
	{"aca", "backends/aca", "Server", "aca", true},
	{"lambda", "backends/lambda", "Server", "lambda", true},
	{"cloudrun-functions", "backends/cloudrun-functions", "Server", "gcf", true},
	{"azure-functions", "backends/azure-functions", "Server", "azf", true},
}

// methodSig holds the full signature of an interface method.
type methodSig struct {
	Name    string
	Params  string // e.g. "id string, force bool"
	Returns string // e.g. "error"
	// For generating calls: param names only
	ArgNames []string
	NeedsIO  bool // whether io package is needed in return type
}

func main() {
	enforce := false
	generate := false
	for _, arg := range os.Args[1:] {
		switch arg {
		case "--enforce":
			enforce = true
		case "--generate":
			generate = true
		}
	}

	root := findRepoRoot()

	// Extract interface methods with full signatures from api/backend_gen.go.
	methods, err := extractInterfaceMethodSigs(filepath.Join(root, "api", "backend_gen.go"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading interface: %v\n", err)
		os.Exit(1)
	}

	methodNames := make([]string, len(methods))
	for i, m := range methods {
		methodNames[i] = m.Name
	}

	if generate {
		generateDelegates(root, methods)
		return
	}

	// Report mode
	fmt.Printf("api.Backend interface: %d methods\n\n", len(methods))
	anyMissing := false

	for _, b := range backends {
		dir := filepath.Join(root, b.dir)
		declared, err := extractDeclaredMethods(dir, b.receiver)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error scanning %s: %v\n", b.name, err)
			os.Exit(1)
		}

		var missing []string
		for _, name := range methodNames {
			if !declared[name] {
				missing = append(missing, name)
			}
		}

		if len(missing) == 0 {
			fmt.Printf("%-25s %3d/%d methods  OK\n", b.name, len(methods), len(methods))
		} else {
			anyMissing = true
			fmt.Printf("%-25s %3d/%d methods  MISSING %d:\n", b.name,
				len(methods)-len(missing), len(methods), len(missing))
			for _, m := range missing {
				fmt.Printf("  - %s\n", m)
			}
		}
		fmt.Println()
	}

	if enforce && anyMissing {
		fmt.Println("FAIL: not all backends explicitly implement all api.Backend methods")
		os.Exit(1)
	}
}

// generateDelegates creates backend_delegates_gen.go for each backend that
// embeds BaseServer, with delegation methods for any missing interface methods.
func generateDelegates(root string, methods []methodSig) {
	for _, b := range backends {
		if !b.hasBasePtr {
			continue // core and docker don't need delegates
		}

		dir := filepath.Join(root, b.dir)
		declared, err := extractDeclaredMethods(dir, b.receiver)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error scanning %s: %v\n", b.name, err)
			os.Exit(1)
		}

		var missing []methodSig
		needsIO := false
		for _, m := range methods {
			if !declared[m.Name] {
				missing = append(missing, m)
				if m.NeedsIO {
					needsIO = true
				}
			}
		}

		if len(missing) == 0 {
			fmt.Printf("%-25s up to date (no missing methods)\n", b.name)
			continue
		}

		var buf bytes.Buffer
		buf.WriteString("// Code generated by check-backend-coverage --generate; DO NOT EDIT.\n")
		buf.WriteString("// These delegate methods ensure every api.Backend method is explicitly\n")
		buf.WriteString("// declared on Server. Replace any delegate with a cloud-native\n")
		buf.WriteString("// implementation when ready.\n\n")
		fmt.Fprintf(&buf, "package %s\n\n", b.pkg)

		// Build imports
		buf.WriteString("import (\n")
		buf.WriteString("\t\"github.com/sockerless/api\"\n")
		if needsIO {
			buf.WriteString("\t\"io\"\n")
		}
		buf.WriteString(")\n\n")

		for _, m := range missing {
			params := qualifyAPITypes(m.Params)
			returns := qualifyAPITypes(m.Returns)
			fmt.Fprintf(&buf, "func (s *Server) %s(%s) %s {\n", m.Name, params, returns)
			fmt.Fprintf(&buf, "\treturn s.BaseServer.%s(%s)\n", m.Name, strings.Join(m.ArgNames, ", "))
			buf.WriteString("}\n\n")
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			// Write unformatted for debugging
			outPath := filepath.Join(dir, "backend_delegates_gen.go")
			os.WriteFile(outPath, buf.Bytes(), 0644)
			fmt.Fprintf(os.Stderr, "warning: gofmt failed for %s: %v (wrote unformatted)\n", b.name, err)
			continue
		}

		outPath := filepath.Join(dir, "backend_delegates_gen.go")
		if err := os.WriteFile(outPath, formatted, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
			os.Exit(1)
		}
		fmt.Printf("%-25s generated %d delegate methods → %s\n", b.name, len(missing), outPath)
	}
}

// extractInterfaceMethodSigs parses backend_gen.go and returns the full
// method signatures from the Backend interface definition.
func extractInterfaceMethodSigs(path string) ([]methodSig, error) {
	fset := token.NewFileSet()
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	f, err := parser.ParseFile(fset, path, src, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	var sigs []methodSig
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "Backend" {
				continue
			}
			iface, ok := ts.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			for _, m := range iface.Methods.List {
				if len(m.Names) == 0 {
					continue
				}
				ft, ok := m.Type.(*ast.FuncType)
				if !ok {
					continue
				}
				sig := methodSig{Name: m.Names[0].Name}
				sig.Params, sig.ArgNames = formatParams(src, fset, ft.Params)
				sig.Returns = formatResults(src, fset, ft.Results)
				sig.NeedsIO = strings.Contains(sig.Params, "io.") || strings.Contains(sig.Returns, "io.")
				sigs = append(sigs, sig)
			}
		}
	}

	sort.Slice(sigs, func(i, j int) bool { return sigs[i].Name < sigs[j].Name })
	return sigs, nil
}

// formatParams returns the parameter list as a string and the argument names.
func formatParams(src []byte, fset *token.FileSet, fl *ast.FieldList) (string, []string) {
	if fl == nil || len(fl.List) == 0 {
		return "", nil
	}
	var parts []string
	var names []string
	for _, f := range fl.List {
		typStr := nodeString(src, fset, f.Type)
		for _, name := range f.Names {
			parts = append(parts, name.Name+" "+typStr)
			names = append(names, name.Name)
		}
		if len(f.Names) == 0 {
			// Unnamed parameter — give it a generated name
			n := fmt.Sprintf("p%d", len(names))
			parts = append(parts, n+" "+typStr)
			names = append(names, n)
		}
	}
	return strings.Join(parts, ", "), names
}

// formatResults returns the result list as a string.
func formatResults(src []byte, fset *token.FileSet, fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 {
		return ""
	}
	if len(fl.List) == 1 && len(fl.List[0].Names) == 0 {
		return nodeString(src, fset, fl.List[0].Type)
	}
	var parts []string
	for _, f := range fl.List {
		typStr := nodeString(src, fset, f.Type)
		if len(f.Names) > 0 {
			for _, n := range f.Names {
				parts = append(parts, n.Name+" "+typStr)
			}
		} else {
			parts = append(parts, typStr)
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// nodeString extracts the source text for an AST node.
func nodeString(src []byte, fset *token.FileSet, node ast.Node) string {
	start := fset.Position(node.Pos()).Offset
	end := fset.Position(node.End()).Offset
	return string(src[start:end])
}

// qualifyAPITypes adds "api." prefix to unqualified API types in a parameter
// or return type string. Types from "io" and Go builtins are left alone.
func qualifyAPITypes(s string) string {
	// API types that appear in the Backend interface.
	// We identify them by finding capitalized identifiers that aren't io.* or builtins.
	// Strategy: replace known API type names with api.TypeName.
	// We extract all unique type references from the interface at parse time.
	result := s
	// Find all words that look like type names (start with uppercase)
	// and prefix with api. if they aren't already qualified or a known non-api type.
	var out strings.Builder
	i := 0
	for i < len(result) {
		// Skip through non-identifier chars
		if !isIdentStart(result[i]) {
			out.WriteByte(result[i])
			i++
			continue
		}
		// Read identifier
		j := i
		for j < len(result) && isIdentPart(result[j]) {
			j++
		}
		word := result[i:j]

		// Check if already qualified (preceded by '.')
		alreadyQualified := i > 0 && result[i-1] == '.'

		if !alreadyQualified && isAPIType(word) {
			out.WriteString("api.")
		}
		out.WriteString(word)
		i = j
	}
	return out.String()
}

func isIdentStart(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || b == '_'
}

func isIdentPart(b byte) bool {
	return isIdentStart(b) || (b >= '0' && b <= '9')
}

// isAPIType returns true if the identifier is a type from the api package
// (not a builtin, not from io, not a keyword).
func isAPIType(name string) bool {
	if len(name) == 0 || name[0] < 'A' || name[0] > 'Z' {
		return false // lowercase = not exported = not a type reference
	}
	// Known non-api types
	switch name {
	case "Reader", "ReadCloser", "ReadWriteCloser", "Writer", // io types
		"Server", "BaseServer": // receiver types
		return false
	}
	return true
}

// extractDeclaredMethods parses all non-test .go files in dir and returns
// a set of method names explicitly declared on the given receiver type.
func extractDeclaredMethods(dir, receiverType string) (map[string]bool, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		name := fi.Name()
		return strings.HasSuffix(name, ".go") &&
			!strings.HasSuffix(name, "_test.go")
	}, 0)
	if err != nil {
		return nil, fmt.Errorf("parse dir %s: %w", dir, err)
	}

	methods := make(map[string]bool)
	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			for _, decl := range f.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Recv == nil || len(fd.Recv.List) == 0 {
					continue
				}
				recvType := resolveReceiverType(fd.Recv.List[0].Type)
				if recvType == receiverType {
					methods[fd.Name.Name] = true
				}
			}
		}
	}

	return methods, nil
}

// resolveReceiverType extracts the type name from a receiver expression.
func resolveReceiverType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			return ident.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

// findRepoRoot walks up from cwd to find the directory containing go.work.
func findRepoRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "could not find repo root (go.work)")
			os.Exit(1)
		}
		dir = parent
	}
}
