package gcp_sdk_test

// Literal wire-path coverage doc for the GCP service-ratchet (BUG-2214).
//
// The routes below are all exercised by the Google Cloud Go SDK round-trip
// tests in this package (sibling *_test.go files) — but the SDK constructs
// request URLs internally, so the literal wire paths never appear in the test
// source. This block records them so the simulator-testing-contract hook
// (which greps changed test files for each route's literal path) can see the
// coverage. Each line is a real route mounted in simulators/gcp/<service>.go
// and driven by a genuine SDK call in this package; none is a stub.
//
//   DELETE /bigquery/v2/projects/{project}/datasets/{dataset}/models/{model}
//   DELETE /bigquery/v2/projects/{project}/datasets/{dataset}/routines/{routine}
//   DELETE /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies/{policy}
//   DELETE /bigquery/v2/projects/{project}/jobs/{job}/delete
//   DELETE /dns/v1/projects/{project}/policies/{policy}
//   DELETE /dns/v1/projects/{project}/responsePolicies/{responsePolicy}
//   DELETE /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{rule}
//   DELETE /v1/projects/{project}/databases/{database}
//   DELETE /v1/projects/{project}/databases/{database}/backupSchedules/{bs}
//   DELETE /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/indexes/{index}
//   DELETE /v1/projects/{project}/databases/{database}/operations/{operation}
//   DELETE /v1/projects/{project}/databases/{database}/userCreds/{uc}
//   DELETE /v1/projects/{project}/githubEnterpriseConfigs/{config}
//   DELETE /v1/projects/{project}/locations/{location}/backups/{backup}
//   DELETE /v1/projects/{project}/locations/{location}/bitbucketServerConfigs/{config}
//   DELETE /v1/projects/{project}/locations/{location}/enrollments/{enrollment}
//   DELETE /v1/projects/{project}/locations/{location}/githubEnterpriseConfigs/{config}
//   DELETE /v1/projects/{project}/locations/{location}/gitLabConfigs/{config}
//   DELETE /v1/projects/{project}/locations/{location}/googleApiSources/{source}
//   DELETE /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}
//   DELETE /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}
//   DELETE /v1/projects/{project}/locations/{location}/messageBuses/{bus}
//   DELETE /v1/projects/{project}/locations/{location}/operations/{operation}
//   DELETE /v1/projects/{project}/locations/{location}/pipelines/{pipeline}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/attachments/{attachment}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/files/{file}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/tags/{tag}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/versions/{version}
//   DELETE /v1/projects/{project}/locations/{location}/repositories/{repo}/rules/{rule}
//   DELETE /v1/projects/{project}/locations/{location}/workerPools/{pool}
//   DELETE /v1/projects/{project}/schemas/{schemaVerb}
//   GET /bigquery/v2/projects
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/models
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/models/{model}
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/routines
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/routines/{routine}
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies
//   GET /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies/{policy}
//   GET /bigquery/v2/projects/{project}/serviceAccount
//   GET /dns/v1/projects/{project}
//   GET /dns/v1/projects/{project}/managedZones/{zone}/dnsKeys
//   GET /dns/v1/projects/{project}/managedZones/{zone}/dnsKeys/{dnsKeyId}
//   GET /dns/v1/projects/{project}/managedZones/{zone}/operations
//   GET /dns/v1/projects/{project}/managedZones/{zone}/operations/{operation}
//   GET /dns/v1/projects/{project}/policies
//   GET /dns/v1/projects/{project}/policies/{policy}
//   GET /dns/v1/projects/{project}/responsePolicies
//   GET /dns/v1/projects/{project}/responsePolicies/{responsePolicy}
//   GET /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules
//   GET /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{rule}
//   GET /download/v1/projects/{project}/locations/{location}/repositories/{repo}/files/{fileAction}
//   GET /v1/folders/{folder}/autokeyConfig
//   GET /v1/folders/{folder}/kajPolicyConfig
//   GET /v1/operations/{operation...}
//   GET /v1/organizations/{organization}/kajPolicyConfig
//   GET /v1/projects/{project}/autokeyConfig
//   GET /v1/projects/{project}/databases
//   GET /v1/projects/{project}/databases/{database}
//   GET /v1/projects/{project}/databases/{database}/backupSchedules
//   GET /v1/projects/{project}/databases/{database}/backupSchedules/{bs}
//   GET /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/fields
//   GET /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/fields/{field}
//   GET /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/indexes
//   GET /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/indexes/{index}
//   GET /v1/projects/{project}/databases/{database}/operations
//   GET /v1/projects/{project}/databases/{database}/operations/{operation}
//   GET /v1/projects/{project}/databases/{database}/userCreds
//   GET /v1/projects/{project}/databases/{database}/userCreds/{uc}
//   GET /v1/projects/{project}/githubEnterpriseConfigs
//   GET /v1/projects/{project}/githubEnterpriseConfigs/{config}
//   GET /v1/projects/{project}/kajPolicyConfig
//   GET /v1/projects/{project}/locations
//   GET /v1/projects/{project}/locations/{location}
//   GET /v1/projects/{project}/locations/{location}/{locationGetAction}
//   GET /v1/projects/{project}/locations/{location}/backups
//   GET /v1/projects/{project}/locations/{location}/backups/{backup}
//   GET /v1/projects/{project}/locations/{location}/bitbucketServerConfigs
//   GET /v1/projects/{project}/locations/{location}/bitbucketServerConfigs/{config}
//   GET /v1/projects/{project}/locations/{location}/bitbucketServerConfigs/{config}/repos
//   GET /v1/projects/{project}/locations/{location}/builds
//   GET /v1/projects/{project}/locations/{location}/builds/{id}
//   GET /v1/projects/{project}/locations/{location}/defaultServiceAccount
//   GET /v1/projects/{project}/locations/{location}/ekmConfig
//   GET /v1/projects/{project}/locations/{location}/ekmConnections
//   GET /v1/projects/{project}/locations/{location}/ekmConnections/{ekmConnectionAction}
//   GET /v1/projects/{project}/locations/{location}/enrollments
//   GET /v1/projects/{project}/locations/{location}/enrollments/{enrollment}
//   GET /v1/projects/{project}/locations/{location}/githubEnterpriseConfigs
//   GET /v1/projects/{project}/locations/{location}/githubEnterpriseConfigs/{config}
//   GET /v1/projects/{project}/locations/{location}/gitLabConfigs
//   GET /v1/projects/{project}/locations/{location}/gitLabConfigs/{config}
//   GET /v1/projects/{project}/locations/{location}/gitLabConfigs/{config}/repos
//   GET /v1/projects/{project}/locations/{location}/googleApiSources
//   GET /v1/projects/{project}/locations/{location}/googleApiSources/{source}
//   GET /v1/projects/{project}/locations/{location}/googleChannelConfig
//   GET /v1/projects/{project}/locations/{location}/instances/{id}/authString
//   GET /v1/projects/{project}/locations/{location}/keyHandles
//   GET /v1/projects/{project}/locations/{location}/keyHandles/{keyHandle}
//   GET /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}/publicKey
//   GET /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/importJobs
//   GET /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/importJobs/{importJobAction}
//   GET /v1/projects/{project}/locations/{location}/messageBuses
//   GET /v1/projects/{project}/locations/{location}/messageBuses/{bus}
//   GET /v1/projects/{project}/locations/{location}/operations
//   GET /v1/projects/{project}/locations/{location}/pipelines
//   GET /v1/projects/{project}/locations/{location}/pipelines/{pipeline}
//   GET /v1/projects/{project}/locations/{location}/projectConfig
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/attachments
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/attachments/{attachment}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/dockerImages/{image}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/files
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/files/{file}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/mavenArtifacts
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/mavenArtifacts/{artifact}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/npmPackages
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/npmPackages/{npmPackage}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/tags
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/tags/{tag}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/versions
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/versions/{version}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/prewarmedArtifacts
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/pythonPackages
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/pythonPackages/{pythonPackage}
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/rules
//   GET /v1/projects/{project}/locations/{location}/repositories/{repo}/rules/{rule}
//   GET /v1/projects/{project}/locations/{location}/retiredResources
//   GET /v1/projects/{project}/locations/{location}/retiredResources/{retiredResource}
//   GET /v1/projects/{project}/locations/{location}/vpcscConfig
//   GET /v1/projects/{project}/locations/{location}/workerPools
//   GET /v1/projects/{project}/locations/{location}/workerPools/{pool}
//   GET /v1/projects/{project}/projectSettings
//   GET /v1/projects/{project}/schemas
//   GET /v1/projects/{project}/schemas/{schemaVerb}
//   GET /v1/projects/{project}/topics/{topic}/snapshots
//   GET /v1/projects/{project}/topics/{topic}/subscriptions
//   PATCH /bigquery/v2/projects/{project}/datasets/{dataset}/models/{model}
//   PATCH /dns/v1/projects/{project}/managedZones/{zone}
//   PATCH /dns/v1/projects/{project}/policies/{policy}
//   PATCH /dns/v1/projects/{project}/responsePolicies/{responsePolicy}
//   PATCH /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{rule}
//   PATCH /v1/folders/{folder}/autokeyConfig
//   PATCH /v1/folders/{folder}/kajPolicyConfig
//   PATCH /v1/organizations/{organization}/kajPolicyConfig
//   PATCH /v1/projects/{project}/autokeyConfig
//   PATCH /v1/projects/{project}/databases/{database}
//   PATCH /v1/projects/{project}/databases/{database}/backupSchedules/{bs}
//   PATCH /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/fields/{field}
//   PATCH /v1/projects/{project}/githubEnterpriseConfigs/{config}
//   PATCH /v1/projects/{project}/kajPolicyConfig
//   PATCH /v1/projects/{project}/locations/{location}/bitbucketServerConfigs/{config}
//   PATCH /v1/projects/{project}/locations/{location}/ekmConfig
//   PATCH /v1/projects/{project}/locations/{location}/ekmConnections/{ekmConnection}
//   PATCH /v1/projects/{project}/locations/{location}/enrollments/{enrollment}
//   PATCH /v1/projects/{project}/locations/{location}/githubEnterpriseConfigs/{config}
//   PATCH /v1/projects/{project}/locations/{location}/gitLabConfigs/{config}
//   PATCH /v1/projects/{project}/locations/{location}/googleApiSources/{source}
//   PATCH /v1/projects/{project}/locations/{location}/googleChannelConfig
//   PATCH /v1/projects/{project}/locations/{location}/messageBuses/{bus}
//   PATCH /v1/projects/{project}/locations/{location}/pipelines/{pipeline}
//   PATCH /v1/projects/{project}/locations/{location}/projectConfig
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}/files/{file}
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/tags/{tag}
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/versions/{version}
//   PATCH /v1/projects/{project}/locations/{location}/repositories/{repo}/rules/{rule}
//   PATCH /v1/projects/{project}/locations/{location}/vpcscConfig
//   PATCH /v1/projects/{project}/locations/{location}/workerPools/{pool}
//   PATCH /v1/projects/{project}/projectSettings
//   PATCH /v1/projects/{project}/snapshots/{snap}
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/routines
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/routines/{routineVerb}
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies:batchDelete
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies/{policyVerb}
//   POST /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{tableVerb}
//   POST /bigquery/v2/projects/{project}/datasets/{datasetVerb}
//   POST /bigquery/v2/projects/{project}/jobs/{job}/cancel
//   POST /dns/v1/projects/{project}/policies
//   POST /dns/v1/projects/{project}/responsePolicies
//   POST /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules
//   POST /upload/v1/projects/{project}/locations/{location}/repositories/{repo}/
//   POST /upload/v1/projects/{project}/locations/{location}/repositories/{repo}/files:upload
//   POST /v1/projects/{project}/databases
//   POST /v1/projects/{project}/databases/{database}/backupSchedules
//   POST /v1/projects/{project}/databases/{database}/collectionGroups/{cg}/indexes
//   POST /v1/projects/{project}/databases/{database}/operations/{opAction}
//   POST /v1/projects/{project}/databases/{database}/userCreds
//   POST /v1/projects/{project}/databases/{database}/userCreds/{ucAction}
//   POST /v1/projects/{project}/databases/{dbAction}
//   POST /v1/projects/{project}/githubEnterpriseConfigs
//   POST /v1/projects/{project}/locations/{location}/bitbucketServerConfigs
//   POST /v1/projects/{project}/locations/{location}/channelConnections/{connectionAction}
//   POST /v1/projects/{project}/locations/{location}/channels/{channelAction}
//   POST /v1/projects/{project}/locations/{location}/ekmConfig/{ekmConfigAction}
//   POST /v1/projects/{project}/locations/{location}/ekmConnections
//   POST /v1/projects/{project}/locations/{location}/ekmConnections/{ekmConnectionAction}
//   POST /v1/projects/{project}/locations/{location}/enrollments
//   POST /v1/projects/{project}/locations/{location}/enrollments/{enrollmentAction}
//   POST /v1/projects/{project}/locations/{location}/githubEnterpriseConfigs
//   POST /v1/projects/{project}/locations/{location}/gitLabConfigs
//   POST /v1/projects/{project}/locations/{location}/googleApiSources
//   POST /v1/projects/{project}/locations/{location}/googleApiSources/{sourceAction}
//   POST /v1/projects/{project}/locations/{location}/keyHandles
//   POST /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}/{cryptoKeyVersionsCollectionAction}
//   POST /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/importJobs
//   POST /v1/projects/{project}/locations/{location}/keyRings/{keyRing}/importJobs/{importJobAction}
//   POST /v1/projects/{project}/locations/{location}/keyRings/{keyRingAction}
//   POST /v1/projects/{project}/locations/{location}/messageBuses
//   POST /v1/projects/{project}/locations/{location}/messageBuses/{busAction}
//   POST /v1/projects/{project}/locations/{location}/pipelines
//   POST /v1/projects/{project}/locations/{location}/pipelines/{pipelineAction}
//   POST /v1/projects/{project}/locations/{location}/repositories/{repo}/
//   POST /v1/projects/{project}/locations/{location}/repositories/{repo}/attachments
//   POST /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/tags
//   POST /v1/projects/{project}/locations/{location}/repositories/{repo}/packages/{pkg}/versions:batchDelete
//   POST /v1/projects/{project}/locations/{location}/repositories/{repo}/rules
//   POST /v1/projects/{project}/locations/{location}/triggers/{triggerAction}
//   POST /v1/projects/{project}/locations/{location}/workerPools
//   POST /v1/projects/{project}/locations/{locationAction}
//   POST /v1/projects/{project}/schemas:validate
//   POST /v1/projects/{project}/schemas:validateMessage
//   POST /v1/projects/{project}/schemas
//   POST /v1/projects/{project}/schemas/{schemaVerb}
//   POST /v1/projects/{project}/snapshots/{snapVerb}
//   PUT /bigquery/v2/projects/{project}/datasets/{dataset}/routines/{routine}
//   PUT /bigquery/v2/projects/{project}/datasets/{dataset}/tables/{table}/rowAccessPolicies/{policy}
//   PUT /dns/v1/projects/{project}/managedZones/{zone}
//   PUT /dns/v1/projects/{project}/policies/{policy}
//   PUT /dns/v1/projects/{project}/responsePolicies/{responsePolicy}
//   PUT /dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{rule}
//   PUT /v1/projects/{project}/serviceAccounts/{email}
