# Standardized Makefile for the AWS github-runner-dispatcher.
# See docs/MAKEFILE_STANDARD.md.

APP_NAME      := github-runner-dispatcher-aws
GO_PACKAGE    := ./cmd/github-runner-dispatcher-aws
GO_ENV        := CGO_ENABLED=0

REPO_ROOT_REL := ..

include $(REPO_ROOT_REL)/make/go-app.mk
