// Code generated by go run ./gen; DO NOT EDIT.

package api

import "io"

// Backend defines the interface that all backends must implement.
type Backend interface {
	// Get system information
	Info() (*BackendInfo, error)
	// Create a container
	ContainerCreate(req *ContainerCreateRequest) (*ContainerCreateResponse, error)
	// Inspect a container
	ContainerInspect(id string) (*Container, error)
	// List containers
	ContainerList(opts ContainerListOptions) ([]*ContainerSummary, error)
	// Start a container
	ContainerStart(id string) error
	// Stop a container
	ContainerStop(id string, timeout *int) error
	// Kill a container
	ContainerKill(id string, signal string) error
	// Remove a container
	ContainerRemove(id string, force bool) error
	// Get container logs
	ContainerLogs(id string, opts ContainerLogsOptions) (io.ReadCloser, error)
	// Wait for a container
	ContainerWait(id string, condition string) (*ContainerWaitResponse, error)
	// Attach to a container
	ContainerAttach(id string, opts ContainerAttachOptions) (io.ReadWriteCloser, error)
	// Restart a container
	ContainerRestart(id string, timeout *int) error
	// List processes in a container
	ContainerTop(id string, psArgs string) (*ContainerTopResponse, error)
	// Delete stopped containers
	ContainerPrune(filters map[string][]string) (*ContainerPruneResponse, error)
	// Get container stats
	ContainerStats(id string, stream bool) (io.ReadCloser, error)
	// Rename a container
	ContainerRename(id string, newName string) error
	// Pause a container
	ContainerPause(id string) error
	// Unpause a container
	ContainerUnpause(id string) error
	// Create an exec instance
	ExecCreate(containerID string, req *ExecCreateRequest) (*ExecCreateResponse, error)
	// Start an exec instance
	ExecStart(id string, opts ExecStartRequest) (io.ReadWriteCloser, error)
	// Inspect an exec instance
	ExecInspect(id string) (*ExecInstance, error)
	// Pull or import an image
	ImagePull(ref string, auth string) (io.ReadCloser, error)
	// Inspect an image
	ImageInspect(name string) (*Image, error)
	// Load images from a tar archive
	ImageLoad(r io.Reader) (io.ReadCloser, error)
	// Tag an image
	ImageTag(source string, repo string, tag string) error
	// List images
	ImageList(opts ImageListOptions) ([]*ImageSummary, error)
	// Remove an image
	ImageRemove(name string, force bool, prune bool) ([]*ImageDeleteResponse, error)
	// Get the history of an image
	ImageHistory(name string) ([]*ImageHistoryEntry, error)
	// Delete unused images
	ImagePrune(filters map[string][]string) (*ImagePruneResponse, error)
	// Check auth configuration
	AuthLogin(req *AuthRequest) (*AuthResponse, error)
	// Create a network
	NetworkCreate(req *NetworkCreateRequest) (*NetworkCreateResponse, error)
	// List networks
	NetworkList(filters map[string][]string) ([]*Network, error)
	// Inspect a network
	NetworkInspect(id string) (*Network, error)
	// Connect a container to a network
	NetworkConnect(id string, req *NetworkConnectRequest) error
	// Disconnect a container from a network
	NetworkDisconnect(id string, req *NetworkDisconnectRequest) error
	// Remove a network
	NetworkRemove(id string) error
	// Delete unused networks
	NetworkPrune(filters map[string][]string) (*NetworkPruneResponse, error)
	// Create a volume
	VolumeCreate(req *VolumeCreateRequest) (*Volume, error)
	// List volumes
	VolumeList(filters map[string][]string) (*VolumeListResponse, error)
	// Inspect a volume
	VolumeInspect(name string) (*Volume, error)
	// Remove a volume
	VolumeRemove(name string, force bool) error
	// Delete unused volumes
	VolumePrune(filters map[string][]string) (*VolumePruneResponse, error)
	// Resize an exec instance TTY
	ExecResize(id string, h, w int) error
	// Resize a container TTY
	ContainerResize(id string, h, w int) error
	// Extract an archive of files into a container
	ContainerPutArchive(id string, path string, noOverwriteDirNonDir bool, body io.Reader) error
	// Get info about files in a container
	ContainerStatPath(id string, path string) (*ContainerPathStat, error)
	// Get an archive of a filesystem resource in a container
	ContainerGetArchive(id string, path string) (*ContainerArchiveResponse, error)
	// Update a container
	ContainerUpdate(id string, req *ContainerUpdateRequest) (*ContainerUpdateResponse, error)
	// Get changes on a container filesystem
	ContainerChanges(id string) ([]ContainerChangeItem, error)
	// Export a container
	ContainerExport(id string) (io.ReadCloser, error)
	// Build an image
	ImageBuild(opts ImageBuildOptions, context io.Reader) (io.ReadCloser, error)
	// Push an image
	ImagePush(name string, tag string, auth string) (io.ReadCloser, error)
	// Export images
	ImageSave(names []string) (io.ReadCloser, error)
	// Search images
	ImageSearch(term string, limit int, filters map[string][]string) ([]*ImageSearchResult, error)
	// Create a new image from a container
	ContainerCommit(req *ContainerCommitRequest) (*ContainerCommitResponse, error)
	// Create a pod
	PodCreate(req *PodCreateRequest) (*PodCreateResponse, error)
	// List pods
	PodList(opts PodListOptions) ([]*PodListEntry, error)
	// Inspect a pod
	PodInspect(name string) (*PodInspectResponse, error)
	// Check if a pod exists
	PodExists(name string) (bool, error)
	// Start a pod
	PodStart(name string) (*PodActionResponse, error)
	// Stop a pod
	PodStop(name string, timeout *int) (*PodActionResponse, error)
	// Kill a pod
	PodKill(name string, signal string) (*PodActionResponse, error)
	// Remove a pod
	PodRemove(name string, force bool) error
	// Monitor events
	SystemEvents(opts EventsOptions) (io.ReadCloser, error)
	// Get data usage information
	SystemDf() (*DiskUsageResponse, error)
}
