// Code generated by go run ./gen; DO NOT EDIT.

package api

import (
	"io"
	"os"
	"time"
)

// AuthRequest is a generated type.
type AuthRequest struct {
	Email         string `json:"email,omitempty"`
	Password      string `json:"password"`
	ServerAddress string `json:"serveraddress"`
	Username      string `json:"username"`
}

// AuthResponse is a generated type.
type AuthResponse struct {
	IdentityToken string `json:"IdentityToken,omitempty"`
	Status        string `json:"Status"`
}

// BackendInfo is a generated type.
type BackendInfo struct {
	Architecture      string `json:"Architecture"`
	Containers        int    `json:"Containers"`
	ContainersPaused  int    `json:"ContainersPaused"`
	ContainersRunning int    `json:"ContainersRunning"`
	ContainersStopped int    `json:"ContainersStopped"`
	Driver            string `json:"Driver"`
	ID                string `json:"ID"`
	Images            int    `json:"Images"`
	KernelVersion     string `json:"KernelVersion"`
	MemTotal          int64  `json:"MemTotal"`
	NCPU              int    `json:"NCPU"`
	Name              string `json:"Name"`
	OSType            string `json:"OSType"`
	OperatingSystem   string `json:"OperatingSystem"`
	ServerVersion     string `json:"ServerVersion"`
}

// BindOptions is a generated type.
type BindOptions struct {
	Propagation string `json:"Propagation,omitempty"`
}

// BuildCache is a generated type.
type BuildCache struct {
	CreatedAt   string `json:"CreatedAt"`
	Description string `json:"Description,omitempty"`
	ID          string `json:"ID"`
	InUse       bool   `json:"InUse"`
	LastUsedAt  string `json:"LastUsedAt,omitempty"`
	Parent      string `json:"Parent,omitempty"`
	Shared      bool   `json:"Shared"`
	Size        int64  `json:"Size"`
	Type        string `json:"Type"`
	UsageCount  int    `json:"UsageCount"`
}

// Container is a generated type.
type Container struct {
	AgentAddress    string          `json:"AgentAddress,omitempty"`
	AgentToken      string          `json:"AgentToken,omitempty"`
	Args            []string        `json:"Args"`
	Config          ContainerConfig `json:"Config"`
	Created         string          `json:"Created"`
	Driver          string          `json:"Driver"`
	ExecIDs         []string        `json:"ExecIDs"`
	HostConfig      HostConfig      `json:"HostConfig"`
	HostnamePath    string          `json:"HostnamePath"`
	HostsPath       string          `json:"HostsPath"`
	ID              string          `json:"Id"`
	Image           string          `json:"Image"`
	LogPath         string          `json:"LogPath"`
	Mounts          []MountPoint    `json:"Mounts"`
	Name            string          `json:"Name"`
	NetworkSettings NetworkSettings `json:"NetworkSettings"`
	Path            string          `json:"Path"`
	Platform        string          `json:"Platform"`
	ResolvConfPath  string          `json:"ResolvConfPath"`
	RestartCount    int             `json:"RestartCount"`
	SizeRootFs      *int64          `json:"SizeRootFs,omitempty"`
	SizeRw          *int64          `json:"SizeRw,omitempty"`
	State           ContainerState  `json:"State"`
}

// ContainerAttachOptions is a generated type.
type ContainerAttachOptions struct {
	DetachKeys string `json:"DetachKeys,omitempty"`
	Logs       bool   `json:"Logs"`
	Stderr     bool   `json:"Stderr"`
	Stdin      bool   `json:"Stdin"`
	Stdout     bool   `json:"Stdout"`
	Stream     bool   `json:"Stream"`
}

// ContainerChangeItem is a generated type.
type ContainerChangeItem struct {
	Kind int    `json:"Kind"`
	Path string `json:"Path"`
}

// ContainerCommitRequest is a generated type.
type ContainerCommitRequest struct {
	Author    string           `json:"author"`
	Changes   []string         `json:"changes,omitempty"`
	Comment   string           `json:"comment"`
	Config    *ContainerConfig `json:"config,omitempty"`
	Container string           `json:"container"`
	Pause     bool             `json:"pause"`
	Repo      string           `json:"repo"`
	Tag       string           `json:"tag"`
}

// ContainerCommitResponse is a generated type.
type ContainerCommitResponse struct {
	ID string `json:"Id"`
}

// ContainerConfig is a generated type.
type ContainerConfig struct {
	ArgsEscaped     bool                `json:"ArgsEscaped,omitempty"`
	AttachStderr    bool                `json:"AttachStderr"`
	AttachStdin     bool                `json:"AttachStdin"`
	AttachStdout    bool                `json:"AttachStdout"`
	Cmd             []string            `json:"Cmd"`
	Domainname      string              `json:"Domainname"`
	Entrypoint      []string            `json:"Entrypoint"`
	Env             []string            `json:"Env"`
	ExposedPorts    map[string]struct{} `json:"ExposedPorts,omitempty"`
	Healthcheck     *HealthcheckConfig  `json:"Healthcheck,omitempty"`
	Hostname        string              `json:"Hostname"`
	Image           string              `json:"Image"`
	Labels          map[string]string   `json:"Labels"`
	MacAddress      string              `json:"MacAddress,omitempty"`
	NetworkDisabled bool                `json:"NetworkDisabled,omitempty"`
	OnBuild         []string            `json:"OnBuild,omitempty"`
	OpenStdin       bool                `json:"OpenStdin"`
	Shell           []string            `json:"Shell,omitempty"`
	StdinOnce       bool                `json:"StdinOnce"`
	StopSignal      string              `json:"StopSignal,omitempty"`
	StopTimeout     *int                `json:"StopTimeout,omitempty"`
	Tty             bool                `json:"Tty"`
	User            string              `json:"User"`
	Volumes         map[string]struct{} `json:"Volumes,omitempty"`
	WorkingDir      string              `json:"WorkingDir"`
}

// ContainerCreateRequest is a generated type.
type ContainerCreateRequest struct {
	*ContainerConfig
	HostConfig       *HostConfig       `json:"HostConfig,omitempty"`
	Name             string            `json:"Name,omitempty"`
	NetworkingConfig *NetworkingConfig `json:"NetworkingConfig,omitempty"`
}

// ContainerCreateResponse is a generated type.
type ContainerCreateResponse struct {
	ID       string   `json:"Id"`
	Warnings []string `json:"Warnings"`
}

// ContainerListOptions is a generated type.
type ContainerListOptions struct {
	All     bool                `json:"All"`
	Filters map[string][]string `json:"Filters,omitempty"`
	Limit   int                 `json:"Limit,omitempty"`
}

// ContainerLogsOptions is a generated type.
type ContainerLogsOptions struct {
	Follow     bool   `json:"Follow"`
	ShowStderr bool   `json:"ShowStderr"`
	ShowStdout bool   `json:"ShowStdout"`
	Since      string `json:"Since"`
	Tail       string `json:"Tail"`
	Timestamps bool   `json:"Timestamps"`
	Until      string `json:"Until"`
}

// ContainerPathStat is a generated type.
type ContainerPathStat struct {
	LinkTarget string      `json:"linkTarget"`
	Mode       os.FileMode `json:"mode"`
	Mtime      time.Time   `json:"mtime"`
	Name       string      `json:"name"`
	Size       int64       `json:"size"`
}

// ContainerPruneResponse is a generated type.
type ContainerPruneResponse struct {
	ContainersDeleted []string `json:"ContainersDeleted"`
	SpaceReclaimed    uint64   `json:"SpaceReclaimed"`
}

// ContainerState is a generated type.
type ContainerState struct {
	Dead       bool         `json:"Dead"`
	Error      string       `json:"Error"`
	ExitCode   int          `json:"ExitCode"`
	FinishedAt string       `json:"FinishedAt"`
	Health     *HealthState `json:"Health,omitempty"`
	OOMKilled  bool         `json:"OOMKilled"`
	Paused     bool         `json:"Paused"`
	Pid        int          `json:"Pid"`
	Restarting bool         `json:"Restarting"`
	Running    bool         `json:"Running"`
	StartedAt  string       `json:"StartedAt"`
	Status     string       `json:"Status"`
}

// ContainerSummary is a generated type.
type ContainerSummary struct {
	Command         string                  `json:"Command"`
	Created         int64                   `json:"Created"`
	HostConfig      *HostConfigSummary      `json:"HostConfig,omitempty"`
	ID              string                  `json:"Id"`
	Image           string                  `json:"Image"`
	ImageID         string                  `json:"ImageID"`
	Labels          map[string]string       `json:"Labels"`
	Mounts          []MountPoint            `json:"Mounts"`
	Names           []string                `json:"Names"`
	NetworkSettings *SummaryNetworkSettings `json:"NetworkSettings,omitempty"`
	Ports           []Port                  `json:"Ports"`
	SizeRootFs      int64                   `json:"SizeRootFs,omitempty"`
	SizeRw          int64                   `json:"SizeRw,omitempty"`
	State           string                  `json:"State"`
	Status          string                  `json:"Status"`
}

// ContainerTopResponse is a generated type.
type ContainerTopResponse struct {
	Processes [][]string `json:"Processes"`
	Titles    []string   `json:"Titles"`
}

// ContainerUpdateRequest is a generated type.
type ContainerUpdateRequest struct {
	BlkioWeight       uint16        `json:"BlkioWeight,omitempty"`
	CPUPeriod         int64         `json:"CpuPeriod,omitempty"`
	CPUQuota          int64         `json:"CpuQuota,omitempty"`
	CPUShares         int64         `json:"CpuShares,omitempty"`
	CpusetCpus        string        `json:"CpusetCpus,omitempty"`
	CpusetMems        string        `json:"CpusetMems,omitempty"`
	Memory            int64         `json:"Memory,omitempty"`
	MemoryReservation int64         `json:"MemoryReservation,omitempty"`
	MemorySwap        int64         `json:"MemorySwap,omitempty"`
	OomKillDisable    *bool         `json:"OomKillDisable,omitempty"`
	PidsLimit         *int64        `json:"PidsLimit,omitempty"`
	RestartPolicy     RestartPolicy `json:"RestartPolicy"`
}

// ContainerUpdateResponse is a generated type.
type ContainerUpdateResponse struct {
	Warnings []string `json:"Warnings"`
}

// ContainerWaitResponse is a generated type.
type ContainerWaitResponse struct {
	Error      *WaitError `json:"Error,omitempty"`
	StatusCode int        `json:"StatusCode"`
}

// DiskUsageResponse is a generated type.
type DiskUsageResponse struct {
	BuildCache []*BuildCache       `json:"BuildCache"`
	Containers []*ContainerSummary `json:"Containers"`
	Images     []*ImageSummary     `json:"Images"`
	LayersSize int64               `json:"LayersSize"`
	Volumes    []*Volume           `json:"Volumes"`
}

// EndpointIPAMConfig is a generated type.
type EndpointIPAMConfig struct {
	IPv4Address  string   `json:"IPv4Address,omitempty"`
	IPv6Address  string   `json:"IPv6Address,omitempty"`
	LinkLocalIPs []string `json:"LinkLocalIPs,omitempty"`
}

// EndpointResource is a generated type.
type EndpointResource struct {
	EndpointID  string `json:"EndpointID"`
	IPv4Address string `json:"IPv4Address"`
	IPv6Address string `json:"IPv6Address"`
	MacAddress  string `json:"MacAddress"`
	Name        string `json:"Name"`
}

// EndpointSettings is a generated type.
type EndpointSettings struct {
	Aliases             []string            `json:"Aliases,omitempty"`
	DNSNames            []string            `json:"DNSNames,omitempty"`
	DriverOpts          map[string]string   `json:"DriverOpts,omitempty"`
	EndpointID          string              `json:"EndpointID"`
	Gateway             string              `json:"Gateway"`
	GlobalIPv6Address   string              `json:"GlobalIPv6Address"`
	GlobalIPv6PrefixLen int                 `json:"GlobalIPv6PrefixLen"`
	IPAMConfig          *EndpointIPAMConfig `json:"IPAMConfig,omitempty"`
	IPAddress           string              `json:"IPAddress"`
	IPPrefixLen         int                 `json:"IPPrefixLen"`
	IPv6Gateway         string              `json:"IPv6Gateway"`
	Links               []string            `json:"Links,omitempty"`
	MacAddress          string              `json:"MacAddress"`
	NetworkID           string              `json:"NetworkID"`
}

// Event is a generated type.
type Event struct {
	Action   string     `json:"Action"`
	Actor    EventActor `json:"Actor"`
	Type     string     `json:"Type"`
	Scope    string     `json:"scope,omitempty"`
	Time     int64      `json:"time"`
	TimeNano int64      `json:"timeNano"`
}

// EventActor is a generated type.
type EventActor struct {
	Attributes map[string]string `json:"Attributes"`
	ID         string            `json:"ID"`
}

// EventsOptions is a generated type.
type EventsOptions struct {
	Filters map[string][]string `json:"Filters,omitempty"`
	Since   string              `json:"Since,omitempty"`
	Until   string              `json:"Until,omitempty"`
}

// ExecCreateRequest is a generated type.
type ExecCreateRequest struct {
	AttachStderr bool     `json:"AttachStderr"`
	AttachStdin  bool     `json:"AttachStdin"`
	AttachStdout bool     `json:"AttachStdout"`
	Cmd          []string `json:"Cmd"`
	DetachKeys   string   `json:"DetachKeys,omitempty"`
	Env          []string `json:"Env,omitempty"`
	Privileged   bool     `json:"Privileged"`
	Tty          bool     `json:"Tty"`
	User         string   `json:"User,omitempty"`
	WorkingDir   string   `json:"WorkingDir,omitempty"`
}

// ExecCreateResponse is a generated type.
type ExecCreateResponse struct {
	ID string `json:"Id"`
}

// ExecInstance is a generated type.
type ExecInstance struct {
	CanRemove     bool              `json:"CanRemove"`
	ContainerID   string            `json:"ContainerID"`
	DetachKeys    string            `json:"DetachKeys,omitempty"`
	ExitCode      int               `json:"ExitCode"`
	ID            string            `json:"ID"`
	OpenStderr    bool              `json:"OpenStderr"`
	OpenStdin     bool              `json:"OpenStdin"`
	OpenStdout    bool              `json:"OpenStdout"`
	Pid           int               `json:"Pid"`
	ProcessConfig ExecProcessConfig `json:"ProcessConfig"`
	Running       bool              `json:"Running"`
}

// ExecProcessConfig is a generated type.
type ExecProcessConfig struct {
	Arguments  []string `json:"arguments"`
	Entrypoint string   `json:"entrypoint"`
	Env        []string `json:"env,omitempty"`
	Privileged *bool    `json:"privileged,omitempty"`
	Tty        bool     `json:"tty"`
	User       string   `json:"user"`
	WorkingDir string   `json:"workingDir,omitempty"`
}

// ExecStartRequest is a generated type.
type ExecStartRequest struct {
	ConsoleSize *[2]uint `json:"ConsoleSize,omitempty"`
	Detach      bool     `json:"Detach"`
	Tty         bool     `json:"Tty"`
}

// GraphDriverData is a generated type.
type GraphDriverData struct {
	Data map[string]string `json:"Data,omitempty"`
	Name string            `json:"Name"`
}

// HealthLog is a generated type.
type HealthLog struct {
	End      string `json:"End"`
	ExitCode int    `json:"ExitCode"`
	Output   string `json:"Output"`
	Start    string `json:"Start"`
}

// HealthState is a generated type.
type HealthState struct {
	FailingStreak int         `json:"FailingStreak"`
	Log           []HealthLog `json:"Log"`
	Status        string      `json:"Status"`
}

// HealthcheckConfig is a generated type.
type HealthcheckConfig struct {
	Interval      int64    `json:"Interval"`
	Retries       int      `json:"Retries"`
	StartInterval int64    `json:"StartInterval"`
	StartPeriod   int64    `json:"StartPeriod"`
	Test          []string `json:"Test"`
	Timeout       int64    `json:"Timeout"`
}

// HostConfig is a generated type.
type HostConfig struct {
	AutoRemove        bool                     `json:"AutoRemove"`
	Binds             []string                 `json:"Binds,omitempty"`
	BlkioWeight       uint16                   `json:"BlkioWeight,omitempty"`
	CapAdd            []string                 `json:"CapAdd,omitempty"`
	CapDrop           []string                 `json:"CapDrop,omitempty"`
	CgroupnsMode      string                   `json:"CgroupnsMode,omitempty"`
	ConsoleSize       [2]uint                  `json:"ConsoleSize,omitempty"`
	CPUPeriod         int64                    `json:"CpuPeriod,omitempty"`
	CPUQuota          int64                    `json:"CpuQuota,omitempty"`
	CPUShares         int64                    `json:"CpuShares,omitempty"`
	CpusetCpus        string                   `json:"CpusetCpus,omitempty"`
	CpusetMems        string                   `json:"CpusetMems,omitempty"`
	DNS               []string                 `json:"Dns,omitempty"`
	DNSOptions        []string                 `json:"DnsOptions,omitempty"`
	DNSSearch         []string                 `json:"DnsSearch,omitempty"`
	ExtraHosts        []string                 `json:"ExtraHosts,omitempty"`
	GroupAdd          []string                 `json:"GroupAdd,omitempty"`
	Init              *bool                    `json:"Init,omitempty"`
	IpcMode           string                   `json:"IpcMode,omitempty"`
	Isolation         string                   `json:"Isolation,omitempty"`
	Links             []string                 `json:"Links,omitempty"`
	LogConfig         LogConfig                `json:"LogConfig"`
	Memory            int64                    `json:"Memory,omitempty"`
	MemoryReservation int64                    `json:"MemoryReservation,omitempty"`
	MemorySwap        int64                    `json:"MemorySwap,omitempty"`
	Mounts            []Mount                  `json:"Mounts,omitempty"`
	NanoCPUs          int64                    `json:"NanoCpus,omitempty"`
	NetworkMode       string                   `json:"NetworkMode"`
	OomKillDisable    *bool                    `json:"OomKillDisable,omitempty"`
	PidMode           string                   `json:"PidMode,omitempty"`
	PidsLimit         *int64                   `json:"PidsLimit,omitempty"`
	PortBindings      map[string][]PortBinding `json:"PortBindings,omitempty"`
	Privileged        bool                     `json:"Privileged,omitempty"`
	PublishAllPorts   bool                     `json:"PublishAllPorts,omitempty"`
	ReadonlyRootfs    bool                     `json:"ReadonlyRootfs,omitempty"`
	RestartPolicy     RestartPolicy            `json:"RestartPolicy"`
	Runtime           string                   `json:"Runtime,omitempty"`
	SecurityOpt       []string                 `json:"SecurityOpt,omitempty"`
	ShmSize           int64                    `json:"ShmSize,omitempty"`
	Sysctls           map[string]string        `json:"Sysctls,omitempty"`
	Tmpfs             map[string]string        `json:"Tmpfs,omitempty"`
	UTSMode           string                   `json:"UTSMode,omitempty"`
	UsernsMode        string                   `json:"UsernsMode,omitempty"`
	VolumesFrom       []string                 `json:"VolumesFrom,omitempty"`
}

// HostConfigSummary is a generated type.
type HostConfigSummary struct {
	NetworkMode string `json:"NetworkMode"`
}

// IPAM is a generated type.
type IPAM struct {
	Config  []IPAMConfig      `json:"Config"`
	Driver  string            `json:"Driver"`
	Options map[string]string `json:"Options,omitempty"`
}

// IPAMConfig is a generated type.
type IPAMConfig struct {
	AuxiliaryAddresses map[string]string `json:"AuxiliaryAddresses,omitempty"`
	Gateway            string            `json:"Gateway"`
	IPRange            string            `json:"IPRange,omitempty"`
	Subnet             string            `json:"Subnet"`
}

// Image is a generated type.
type Image struct {
	Architecture  string          `json:"Architecture"`
	Author        string          `json:"Author,omitempty"`
	Comment       string          `json:"Comment,omitempty"`
	Config        ContainerConfig `json:"Config"`
	Created       string          `json:"Created"`
	DockerVersion string          `json:"DockerVersion,omitempty"`
	GraphDriver   GraphDriverData `json:"GraphDriver"`
	ID            string          `json:"Id"`
	Metadata      ImageMetadata   `json:"Metadata"`
	Os            string          `json:"Os"`
	Parent        string          `json:"Parent,omitempty"`
	RepoDigests   []string        `json:"RepoDigests"`
	RepoTags      []string        `json:"RepoTags"`
	RootFS        RootFS          `json:"RootFS"`
	Size          int64           `json:"Size"`
	VirtualSize   int64           `json:"VirtualSize"`
}

// ImageBuildOptions is a generated type.
type ImageBuildOptions struct {
	BuildArgs    map[string]*string `json:"buildArgs,omitempty"`
	CacheFrom    []string           `json:"cacheFrom,omitempty"`
	CacheTo      []string           `json:"cacheTo,omitempty"`
	CgroupParent string             `json:"cgroupParent,omitempty"`
	CPUPeriod    int64              `json:"cpuPeriod,omitempty"`
	CPUQuota     int64              `json:"cpuQuota,omitempty"`
	CPUSetCPUs   string             `json:"cpuSetCpus,omitempty"`
	CPUShares    int64              `json:"cpuShares,omitempty"`
	Dockerfile   string             `json:"dockerfile"`
	ExtraHosts   string             `json:"extraHosts,omitempty"`
	ForceRemove  bool               `json:"forceRemove"`
	Labels       map[string]string  `json:"labels,omitempty"`
	Memory       int64              `json:"memory,omitempty"`
	MemorySwap   int64              `json:"memswap,omitempty"`
	NetworkMode  string             `json:"networkMode,omitempty"`
	NoCache      bool               `json:"noCache"`
	Outputs      string             `json:"outputs,omitempty"`
	Platform     string             `json:"platform,omitempty"`
	Pull         string             `json:"pull,omitempty"`
	Quiet        bool               `json:"quiet"`
	Remote       string             `json:"remote,omitempty"`
	Remove       bool               `json:"remove"`
	Secrets      map[string]string  `json:"secrets,omitempty"`
	ShmSize      int64              `json:"shmSize,omitempty"`
	Squash       bool               `json:"squash,omitempty"`
	Tags         []string           `json:"tags,omitempty"`
	Target       string             `json:"target,omitempty"`
	Version      string             `json:"version,omitempty"`
}

// ImageDeleteResponse is a generated type.
type ImageDeleteResponse struct {
	Deleted  string `json:"Deleted,omitempty"`
	Untagged string `json:"Untagged,omitempty"`
}

// ImageHistoryEntry is a generated type.
type ImageHistoryEntry struct {
	Comment   string   `json:"Comment"`
	Created   int64    `json:"Created"`
	CreatedBy string   `json:"CreatedBy"`
	ID        string   `json:"Id"`
	Size      int64    `json:"Size"`
	Tags      []string `json:"Tags"`
}

// ImageListOptions is a generated type.
type ImageListOptions struct {
	All     bool                `json:"All"`
	Filters map[string][]string `json:"Filters,omitempty"`
}

// ImageMetadata is a generated type.
type ImageMetadata struct {
	LastTagTime string `json:"LastTagTime,omitempty"`
}

// ImagePruneResponse is a generated type.
type ImagePruneResponse struct {
	ImagesDeleted  []*ImageDeleteResponse `json:"ImagesDeleted"`
	SpaceReclaimed uint64                 `json:"SpaceReclaimed"`
}

// ImagePullRequest is a generated type.
type ImagePullRequest struct {
	Auth      string `json:"Auth,omitempty"`
	Platform  string `json:"Platform,omitempty"`
	Reference string `json:"Reference"`
}

// ImageSearchResult is a generated type.
type ImageSearchResult struct {
	Description string `json:"description"`
	IsAutomated bool   `json:"is_automated"`
	IsOfficial  bool   `json:"is_official"`
	Name        string `json:"name"`
	StarCount   int    `json:"star_count"`
}

// ImageSummary is a generated type.
type ImageSummary struct {
	Containers  int64             `json:"Containers"`
	Created     int64             `json:"Created"`
	ID          string            `json:"Id"`
	Labels      map[string]string `json:"Labels"`
	ParentID    string            `json:"ParentId"`
	RepoDigests []string          `json:"RepoDigests"`
	RepoTags    []string          `json:"RepoTags"`
	SharedSize  int64             `json:"SharedSize"`
	Size        int64             `json:"Size"`
	VirtualSize int64             `json:"VirtualSize"`
}

// LogConfig is a generated type.
type LogConfig struct {
	Config map[string]string `json:"Config"`
	Type   string            `json:"Type"`
}

// Mount is a generated type.
type Mount struct {
	BindOptions   *BindOptions   `json:"BindOptions,omitempty"`
	Consistency   string         `json:"Consistency,omitempty"`
	ReadOnly      bool           `json:"ReadOnly,omitempty"`
	Source        string         `json:"Source"`
	Target        string         `json:"Target"`
	TmpfsOptions  *TmpfsOptions  `json:"TmpfsOptions,omitempty"`
	Type          string         `json:"Type"`
	VolumeOptions *VolumeOptions `json:"VolumeOptions,omitempty"`
}

// MountPoint is a generated type.
type MountPoint struct {
	Destination string `json:"Destination"`
	Driver      string `json:"Driver,omitempty"`
	Mode        string `json:"Mode"`
	Name        string `json:"Name,omitempty"`
	Propagation string `json:"Propagation,omitempty"`
	RW          bool   `json:"RW"`
	Source      string `json:"Source"`
	Type        string `json:"Type"`
}

// Network is a generated type.
type Network struct {
	Attachable bool                        `json:"Attachable"`
	Containers map[string]EndpointResource `json:"Containers"`
	Created    string                      `json:"Created"`
	Driver     string                      `json:"Driver"`
	EnableIPv6 bool                        `json:"EnableIPv6"`
	IPAM       IPAM                        `json:"IPAM"`
	ID         string                      `json:"Id"`
	Ingress    bool                        `json:"Ingress"`
	Internal   bool                        `json:"Internal"`
	Labels     map[string]string           `json:"Labels"`
	Name       string                      `json:"Name"`
	Options    map[string]string           `json:"Options"`
	Scope      string                      `json:"Scope"`
}

// NetworkConnectRequest is a generated type.
type NetworkConnectRequest struct {
	Container      string            `json:"Container"`
	EndpointConfig *EndpointSettings `json:"EndpointConfig,omitempty"`
}

// NetworkCreateRequest is a generated type.
type NetworkCreateRequest struct {
	Attachable     bool              `json:"Attachable"`
	CheckDuplicate bool              `json:"CheckDuplicate"`
	Driver         string            `json:"Driver"`
	EnableIPv6     bool              `json:"EnableIPv6"`
	IPAM           *IPAM             `json:"IPAM,omitempty"`
	Ingress        bool              `json:"Ingress"`
	Internal       bool              `json:"Internal"`
	Labels         map[string]string `json:"Labels,omitempty"`
	Name           string            `json:"Name"`
	Options        map[string]string `json:"Options,omitempty"`
}

// NetworkCreateResponse is a generated type.
type NetworkCreateResponse struct {
	ID      string `json:"Id"`
	Warning string `json:"Warning"`
}

// NetworkDisconnectRequest is a generated type.
type NetworkDisconnectRequest struct {
	Container string `json:"Container"`
	Force     bool   `json:"Force"`
}

// NetworkPruneResponse is a generated type.
type NetworkPruneResponse struct {
	NetworksDeleted []string `json:"NetworksDeleted"`
}

// NetworkSettings is a generated type.
type NetworkSettings struct {
	Bridge                 string                       `json:"Bridge"`
	EndpointID             string                       `json:"EndpointID"`
	Gateway                string                       `json:"Gateway"`
	GlobalIPv6Address      string                       `json:"GlobalIPv6Address"`
	GlobalIPv6PrefixLen    int                          `json:"GlobalIPv6PrefixLen"`
	HairpinMode            bool                         `json:"HairpinMode"`
	IPAddress              string                       `json:"IPAddress"`
	IPPrefixLen            int                          `json:"IPPrefixLen"`
	IPv6Gateway            string                       `json:"IPv6Gateway"`
	LinkLocalIPv6Address   string                       `json:"LinkLocalIPv6Address"`
	LinkLocalIPv6PrefixLen int                          `json:"LinkLocalIPv6PrefixLen"`
	MacAddress             string                       `json:"MacAddress"`
	Networks               map[string]*EndpointSettings `json:"Networks"`
	Ports                  map[string][]PortBinding     `json:"Ports"`
	SandboxID              string                       `json:"SandboxID"`
	SandboxKey             string                       `json:"SandboxKey"`
}

// NetworkingConfig is a generated type.
type NetworkingConfig struct {
	EndpointsConfig map[string]*EndpointSettings `json:"EndpointsConfig,omitempty"`
}

// PodActionResponse is a generated type.
type PodActionResponse struct {
	Errs     []string `json:"Errs"`
	ID       string   `json:"Id"`
	RawInput string   `json:"RawInput"`
}

// PodBlkioDeviceRate is a generated type.
type PodBlkioDeviceRate struct {
	Path string `json:"Path"`
	Rate uint64 `json:"Rate"`
}

// PodContainerInfo is a generated type.
type PodContainerInfo struct {
	ID    string `json:"Id"`
	Name  string `json:"Name"`
	State string `json:"State"`
}

// PodCreateRequest is a generated type.
type PodCreateRequest struct {
	Hostname string            `json:"hostname,omitempty"`
	Labels   map[string]string `json:"labels,omitempty"`
	Name     string            `json:"name"`
	NoInfra  bool              `json:"no_infra,omitempty"`
	Share    string            `json:"share,omitempty"`
}

// PodCreateResponse is a generated type.
type PodCreateResponse struct {
	ID string `json:"Id"`
}

// PodInfraConfig is a generated type.
type PodInfraConfig struct {
	DNSOption          []string                 `json:"DNSOption"`
	DNSSearch          []string                 `json:"DNSSearch"`
	DNSServer          []string                 `json:"DNSServer"`
	HostAdd            []string                 `json:"HostAdd"`
	HostNetwork        bool                     `json:"HostNetwork"`
	NetworkOptions     map[string][]string      `json:"NetworkOptions"`
	Networks           []string                 `json:"Networks"`
	NoManageHosts      bool                     `json:"NoManageHosts"`
	NoManageResolvConf bool                     `json:"NoManageResolvConf"`
	PortBindings       map[string][]PortBinding `json:"PortBindings"`
	StaticIP           string                   `json:"StaticIP"`
	StaticMAC          string                   `json:"StaticMAC"`
	Pid_ns             string                   `json:"pid_ns"`
	Userns             string                   `json:"userns"`
	Uts_ns             string                   `json:"uts_ns"`
}

// PodInspectDevice is a generated type.
type PodInspectDevice struct {
	CgroupPermissions string `json:"CgroupPermissions"`
	PathInContainer   string `json:"PathInContainer"`
	PathOnHost        string `json:"PathOnHost"`
}

// PodInspectMount is a generated type.
type PodInspectMount struct {
	Destination string `json:"Destination"`
	Mode        string `json:"Mode"`
	RW          bool   `json:"RW"`
	Source      string `json:"Source"`
	Type        string `json:"Type"`
}

// PodInspectResponse is a generated type.
type PodInspectResponse struct {
	BlkioDeviceReadBps  []PodBlkioDeviceRate `json:"BlkioDeviceReadBps"`
	BlkioDeviceWriteBps []PodBlkioDeviceRate `json:"BlkioDeviceWriteBps"`
	BlkioWeight         int                  `json:"BlkioWeight"`
	CPUPeriod           uint64               `json:"CPUPeriod"`
	CPUQuota            int64                `json:"CPUQuota"`
	CPUSetCPUs          string               `json:"CPUSetCPUs"`
	CPUShares           uint64               `json:"CPUShares"`
	CgroupParent        string               `json:"CgroupParent"`
	CgroupPath          string               `json:"CgroupPath"`
	Containers          []PodContainerInfo   `json:"Containers"`
	CreateCommand       []string             `json:"CreateCommand"`
	Created             string               `json:"Created"`
	ExitPolicy          string               `json:"ExitPolicy"`
	Hostname            string               `json:"Hostname"`
	ID                  string               `json:"Id"`
	InfraConfig         PodInfraConfig       `json:"InfraConfig"`
	InfraContainerID    string               `json:"InfraContainerID"`
	Labels              map[string]string    `json:"Labels"`
	LockNumber          int                  `json:"LockNumber"`
	MemoryLimit         uint64               `json:"MemoryLimit"`
	MemorySwap          uint64               `json:"MemorySwap"`
	Name                string               `json:"Name"`
	Namespace           string               `json:"Namespace"`
	NumContainers       int                  `json:"NumContainers"`
	RestartPolicy       string               `json:"RestartPolicy"`
	SecurityOpts        []string             `json:"SecurityOpts"`
	SharedNamespaces    []string             `json:"SharedNamespaces"`
	State               string               `json:"State"`
	VolumesFrom         []string             `json:"VolumesFrom"`
	Device_read_bps     []PodBlkioDeviceRate `json:"device_read_bps"`
	Devices             []PodInspectDevice   `json:"devices"`
	Mounts              []PodInspectMount    `json:"mounts"`
}

// PodListEntry is a generated type.
type PodListEntry struct {
	Containers []PodContainerInfo `json:"Containers"`
	Created    string             `json:"Created"`
	ID         string             `json:"Id"`
	Labels     map[string]string  `json:"Labels"`
	Name       string             `json:"Name"`
	Status     string             `json:"Status"`
}

// PodListOptions is a generated type.
type PodListOptions struct {
	Filters map[string][]string `json:"Filters,omitempty"`
}

// Port is a generated type.
type Port struct {
	IP          string `json:"IP"`
	PrivatePort uint16 `json:"PrivatePort"`
	PublicPort  uint16 `json:"PublicPort"`
	Type        string `json:"Type"`
}

// PortBinding is a generated type.
type PortBinding struct {
	HostIP   string `json:"HostIp"`
	HostPort string `json:"HostPort"`
}

// RestartPolicy is a generated type.
type RestartPolicy struct {
	MaximumRetryCount int    `json:"MaximumRetryCount"`
	Name              string `json:"Name"`
}

// RootFS is a generated type.
type RootFS struct {
	Layers []string `json:"Layers,omitempty"`
	Type   string   `json:"Type"`
}

// SummaryNetworkSettings is a generated type.
type SummaryNetworkSettings struct {
	Networks map[string]*EndpointSettings `json:"Networks"`
}

// TmpfsOptions is a generated type.
type TmpfsOptions struct {
	Mode      uint32 `json:"Mode,omitempty"`
	SizeBytes int64  `json:"SizeBytes,omitempty"`
}

// Volume is a generated type.
type Volume struct {
	CreatedAt  string            `json:"CreatedAt,omitempty"`
	Driver     string            `json:"Driver"`
	Labels     map[string]string `json:"Labels"`
	Mountpoint string            `json:"Mountpoint"`
	Name       string            `json:"Name"`
	Options    map[string]string `json:"Options"`
	Scope      string            `json:"Scope"`
	Status     map[string]any    `json:"Status,omitempty"`
	UsageData  *VolumeUsageData  `json:"UsageData,omitempty"`
}

// VolumeCreateRequest is a generated type.
type VolumeCreateRequest struct {
	Driver     string            `json:"Driver,omitempty"`
	DriverOpts map[string]string `json:"DriverOpts,omitempty"`
	Labels     map[string]string `json:"Labels,omitempty"`
	Name       string            `json:"Name,omitempty"`
}

// VolumeDriverConfig is a generated type.
type VolumeDriverConfig struct {
	Name    string            `json:"Name,omitempty"`
	Options map[string]string `json:"Options,omitempty"`
}

// VolumeListResponse is a generated type.
type VolumeListResponse struct {
	Volumes  []*Volume `json:"Volumes"`
	Warnings []string  `json:"Warnings"`
}

// VolumeOptions is a generated type.
type VolumeOptions struct {
	DriverConfig *VolumeDriverConfig `json:"DriverConfig,omitempty"`
	Labels       map[string]string   `json:"Labels,omitempty"`
	NoCopy       bool                `json:"NoCopy,omitempty"`
}

// VolumePruneResponse is a generated type.
type VolumePruneResponse struct {
	SpaceReclaimed uint64   `json:"SpaceReclaimed"`
	VolumesDeleted []string `json:"VolumesDeleted"`
}

// VolumeUsageData is a generated type.
type VolumeUsageData struct {
	RefCount int64 `json:"RefCount"`
	Size     int64 `json:"Size"`
}

// WaitError is a generated type.
type WaitError struct {
	Message string `json:"Message"`
}

// ContainerArchiveResponse wraps the stat and reader for a container archive get.
type ContainerArchiveResponse struct {
	Stat   ContainerPathStat
	Reader io.ReadCloser
}
